# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1092, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftside_panel = QtWidgets.QFrame(self.centralwidget)
        self.leftside_panel.setGeometry(QtCore.QRect(-11, -1, 141, 581))
        self.leftside_panel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.leftside_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftside_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftside_panel.setObjectName("leftside_panel")
        self.exit_button = QtWidgets.QPushButton(self.leftside_panel)
        self.exit_button.setGeometry(QtCore.QRect(10, 540, 131, 51))
        self.exit_button.setStyleSheet("background-color: rgb(255, 68, 55);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/NCproject/Icons/logout (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon)
        self.exit_button.setIconSize(QtCore.QSize(30, 30))
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.Setting_Button = QtWidgets.QPushButton(self.leftside_panel)
        self.Setting_Button.setGeometry(QtCore.QRect(10, 310, 131, 51))
        self.Setting_Button.setStyleSheet("background-color: rgb(85, 170, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/NCproject/Icons/setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Setting_Button.setIcon(icon1)
        self.Setting_Button.setIconSize(QtCore.QSize(30, 30))
        self.Setting_Button.setObjectName("Setting_Button")
        self.Help_button = QtWidgets.QPushButton(self.leftside_panel)
        self.Help_button.setGeometry(QtCore.QRect(10, 360, 131, 51))
        self.Help_button.setStyleSheet("background-color: rgb(85, 170, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:/NCproject/Icons/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help_button.setIcon(icon2)
        self.Help_button.setIconSize(QtCore.QSize(30, 30))
        self.Help_button.setObjectName("Help_button")
        self.Logo_button = QtWidgets.QPushButton(self.leftside_panel)
        self.Logo_button.setGeometry(QtCore.QRect(10, 2, 131, 81))
        self.Logo_button.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.Logo_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:/NCproject/Icons/teamwork.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Logo_button.setIcon(icon3)
        self.Logo_button.setIconSize(QtCore.QSize(60, 60))
        self.Logo_button.setAutoDefault(False)
        self.Logo_button.setDefault(False)
        self.Logo_button.setFlat(False)
        self.Logo_button.setObjectName("Logo_button")
        self.History_button = QtWidgets.QPushButton(self.leftside_panel)
        self.History_button.setGeometry(QtCore.QRect(10, 260, 131, 51))
        self.History_button.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:/NCproject/Icons/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.History_button.setIcon(icon4)
        self.History_button.setIconSize(QtCore.QSize(30, 30))
        self.History_button.setCheckable(False)
        self.History_button.setAutoExclusive(False)
        self.History_button.setFlat(False)
        self.History_button.setObjectName("History_button")
        self.Brand_name = QtWidgets.QLabel(self.leftside_panel)
        self.Brand_name.setGeometry(QtCore.QRect(16, 89, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.Brand_name.setFont(font)
        self.Brand_name.setTextFormat(QtCore.Qt.AutoText)
        self.Brand_name.setScaledContents(False)
        self.Brand_name.setAlignment(QtCore.Qt.AlignCenter)
        self.Brand_name.setObjectName("Brand_name")
        self.extra_button = QtWidgets.QPushButton(self.leftside_panel)
        self.extra_button.setGeometry(QtCore.QRect(10, 410, 131, 51))
        self.extra_button.setStyleSheet("background-color: rgb(85, 170, 255);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:/NCproject/Icons/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.extra_button.setIcon(icon5)
        self.extra_button.setIconSize(QtCore.QSize(30, 30))
        self.extra_button.setObjectName("extra_button")
        self.Top_frame = QtWidgets.QFrame(self.centralwidget)
        self.Top_frame.setGeometry(QtCore.QRect(130, 0, 961, 121))
        self.Top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_frame.setObjectName("Top_frame")
        self.label = QtWidgets.QLabel(self.Top_frame)
        self.label.setGeometry(QtCore.QRect(6, -1, 961, 51))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Top_frame)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 961, 31))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Top_frame)
        self.label_3.setGeometry(QtCore.QRect(0, 65, 961, 51))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.Main_frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_frame.setGeometry(QtCore.QRect(130, 130, 971, 451))
        self.Main_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_frame.setObjectName("Main_frame")
        self.pushButton_2 = QtWidgets.QPushButton(self.Main_frame)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 10, 531, 101))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(57, 126, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Main_frame)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 80, 531, 101))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 0, 127);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.Main_frame)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 150, 531, 101))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 138, 5);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.Main_frame)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 220, 531, 101))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.Main_frame)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 290, 531, 101))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.Main_frame)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 360, 531, 101))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 85, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_button.setText(_translate("MainWindow", "        Exit      "))
        self.Setting_Button.setText(_translate("MainWindow", "        Settings "))
        self.Help_button.setText(_translate("MainWindow", "         Help      "))
        self.History_button.setText(_translate("MainWindow", "          History   "))
        self.Brand_name.setText(_translate("MainWindow", "The High Five"))
        self.extra_button.setText(_translate("MainWindow", "        About   "))
        self.label.setText(_translate("MainWindow", "Welcome to Numerical Computing Project "))
        self.label_2.setText(_translate("MainWindow", "By"))
        self.label_3.setText(_translate("MainWindow", "The High Five"))
        self.pushButton_2.setText(_translate("MainWindow", "Solution(Root) of equations in one variable"))
        self.pushButton_3.setText(_translate("MainWindow", "Interpolation and Polynomial approximation"))
        self.pushButton_4.setText(_translate("MainWindow", "Numerical Differentiation and  Integration"))
        self.pushButton_5.setText(_translate("MainWindow", "Differential Equations"))
        self.pushButton_6.setText(_translate("MainWindow", "Direct Methodfor solving linear system"))
        self.pushButton_7.setText(_translate("MainWindow", "Iterative Techniques"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
